/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Resource = {
  _type: "resource";
  type?: "link";
  title: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?: string;
  title: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type VideoChunk = {
  _id: string;
  _type: "videoChunk";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lesson: LessonReference;
  videoId?: string;
  chunkIndex: number;
  start: number;
  end: number;
  text: string;
  chapter?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  videoUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Module = {
  _type: "module";
  title: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  instructor: InstructorReference;
  category: CategoryReference;
  level: "beginner" | "intermediate" | "advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  icon?:
    | "nextjs"
    | "docker"
    | "typescript"
    | "react"
    | "nodejs"
    | "database"
    | "devops";
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  title?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  expertise?: Array<string>;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  socialLinks?: Array<{
    platform: "website" | "github" | "x" | "linkedin" | "youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type SanityAgentContextConversation = {
  _id: string;
  _type: "sanity.agentContextConversation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  agentId: string;
  threadId: string;
  messages?: Array<{
    role: "user" | "assistant" | "system" | "tool";
    content?: string;
    toolName?: string;
    toolType?: "call" | "result";
    _type: "conversationMessage";
    _key: string;
  }>;
  startedAt?: string;
  messagesUpdatedAt?: string;
  modelProvider?: string;
  modelId?: string;
  tokenUsage?: {
    inputTokens?: number;
    outputTokens?: number;
    totalTokens?: number;
  };
  coreMetrics?: {
    successScore?: number;
    sentiment?: "positive" | "neutral" | "negative";
    contentGaps?: Array<string>;
  };
  classifiedAt?: string;
  classificationError?: string;
};

export type SanityAgentContext = {
  _id: string;
  _type: "sanity.agentContext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  version?: string;
  name?: string;
  slug: Slug;
  groqFilter?: string;
  instructions?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Resource
  | LearningOutcome
  | LessonReference
  | VideoChunk
  | SanityImageAssetReference
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Module
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityAgentContextConversation
  | SanityAgentContext
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)]  | order(title asc) {      _id,  title,  "slug": slug.current,  summary,  level,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "category": category->{ _id, title, "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  price,  popular,  studentCount,  "lessonCount": count(modules[].lessons[]),  "moduleCount": count(modules),  "totalDuration": math::sum(modules[].lessons[]->duration)  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  level: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  coverImageAlt: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  };
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  lessonCount: number | null;
  moduleCount: number | null;
  totalDuration: number | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  summary,  level,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "category": category->{ _id, title, "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  price,  popular,  studentCount,  "lessonCount": count(modules[].lessons[]),  "moduleCount": count(modules),  "totalDuration": math::sum(modules[].lessons[]->duration),    "learningOutcomes": learningOutcomes[] { _key, icon, title, description },    "modules": modules[] { _key, title, summary, "lessons": lessons[]->{   _id,  title,  "slug": slug.current,  duration,  freePreview } }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string;
  level: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  coverImageAlt: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  };
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  lessonCount: number | null;
  moduleCount: number | null;
  totalDuration: number | null;
  learningOutcomes: Array<{
    _key: string;
    icon: string | null;
    title: string;
    description: string | null;
  }> | null;
  modules: Array<{
    _key: string;
    title: string;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      duration: number | null;
      freePreview: boolean | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)].slug.current
export type COURSE_SLUGS_QUERY_RESULT = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: COURSES_BY_INSTRUCTOR_QUERY
// Query: *[_type == "course" && defined(slug.current) && instructor._ref == $instructorId]  | order(title asc) {      _id,  title,  "slug": slug.current,  summary,  level,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "category": category->{ _id, title, "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  price,  popular,  studentCount,  "lessonCount": count(modules[].lessons[]),  "moduleCount": count(modules),  "totalDuration": math::sum(modules[].lessons[]->duration)  }
export type COURSES_BY_INSTRUCTOR_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  level: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  coverImageAlt: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  };
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  lessonCount: number | null;
  moduleCount: number | null;
  totalDuration: number | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: COURSES_BY_CATEGORY_QUERY
// Query: *[_type == "course" && defined(slug.current) && category._ref == $categoryId]  | order(title asc) {      _id,  title,  "slug": slug.current,  summary,  level,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "category": category->{ _id, title, "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  price,  popular,  studentCount,  "lessonCount": count(modules[].lessons[]),  "moduleCount": count(modules),  "totalDuration": math::sum(modules[].lessons[]->duration)  }
export type COURSES_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string;
  level: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  coverImageAlt: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
  };
  instructor: {
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  };
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  lessonCount: number | null;
  moduleCount: number | null;
  totalDuration: number | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    icon,    "courseCount": count(      *[_type == "course" && references(^._id)]    )  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  icon:
    | "database"
    | "devops"
    | "docker"
    | "nextjs"
    | "nodejs"
    | "react"
    | "typescript"
    | null;
  courseCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    icon,    "courses": *[_type == "course" && references(^._id)] | order(title asc) {        _id,  title,  "slug": slug.current,  summary,  level,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "category": category->{ _id, title, "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  price,  popular,  studentCount,  "lessonCount": count(modules[].lessons[]),  "moduleCount": count(modules),  "totalDuration": math::sum(modules[].lessons[]->duration)    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  icon:
    | "database"
    | "devops"
    | "docker"
    | "nextjs"
    | "nodejs"
    | "react"
    | "typescript"
    | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    level: "advanced" | "beginner" | "intermediate";
    coverImageUrl: string | null;
    coverImageAlt: string | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    instructor: {
      _id: string;
      name: string;
      slug: string;
      title: string | null;
      photoUrl: string | null;
    };
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    lessonCount: number | null;
    moduleCount: number | null;
    totalDuration: number | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor"] | order(name asc) {    _id,    name,    "slug": slug.current,    title,    bio,    "photoUrl": photo.asset->url,    expertise,    "socialLinks": socialLinks[] { _key, platform, url },    "courseCount": count(      *[_type == "course" && references(^._id)]    )  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  title: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  photoUrl: string | null;
  expertise: Array<string> | null;
  socialLinks: Array<{
    _key: string;
    platform: "github" | "linkedin" | "website" | "x" | "youtube";
    url: string | null;
  }> | null;
  courseCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    title,    bio,    "photoUrl": photo.asset->url,    expertise,    "socialLinks": socialLinks[] { _key, platform, url },    "courses": *[_type == "course" && references(^._id)] | order(title asc) {        _id,  title,  "slug": slug.current,  summary,  level,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "category": category->{ _id, title, "slug": slug.current },  "instructor": instructor->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  price,  popular,  studentCount,  "lessonCount": count(modules[].lessons[]),  "moduleCount": count(modules),  "totalDuration": math::sum(modules[].lessons[]->duration)    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  title: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  photoUrl: string | null;
  expertise: Array<string> | null;
  socialLinks: Array<{
    _key: string;
    platform: "github" | "linkedin" | "website" | "x" | "youtube";
    url: string | null;
  }> | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    summary: string;
    level: "advanced" | "beginner" | "intermediate";
    coverImageUrl: string | null;
    coverImageAlt: string | null;
    category: {
      _id: string;
      title: string;
      slug: string;
    };
    instructor: {
      _id: string;
      name: string;
      slug: string;
      title: string | null;
      photoUrl: string | null;
    };
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    lessonCount: number | null;
    moduleCount: number | null;
    totalDuration: number | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    "thumbnailUrl": thumbnail.asset->url,    duration,    freePreview,    studentCount,    "notes": notes[] {      _type == "image" => {        _type,        _key,        "url": asset->url,        alt,        caption      },      _type != "image" => @    },    keyPoints,    proTip,    "resources": resources[] { _key, type, title, description, url },    "course": *[_type == "course" && references(^._id)][0] {      _id,      title,      "slug": slug.current,      level,      studentCount,      "coverImageUrl": coverImage.asset->url,      "modules": modules[] {        _key,        title,        summary,        "lessons": lessons[]-> {          _id,          title,          "slug": slug.current,          duration,          freePreview        }      }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  videoUrl: string | null;
  thumbnailUrl: string | null;
  duration: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  notes: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _type: "image";
        _key: string;
        url: string | null;
        alt: string | null;
        caption: string | null;
      }
  > | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "link" | null;
    title: string;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string;
    slug: string;
    level: "advanced" | "beginner" | "intermediate";
    studentCount: number | null;
    coverImageUrl: string | null;
    modules: Array<{
      _key: string;
      title: string;
      summary: string | null;
      lessons: Array<{
        _id: string;
        title: string;
        slug: string;
        duration: number | null;
        freePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)].slug.current
export type LESSON_SLUGS_QUERY_RESULT = Array<string>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)]\n  | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  "coverImageUrl": coverImage.asset->url,\n  "coverImageAlt": coverImage.alt,\n  "category": category->{ _id, title, "slug": slug.current },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  price,\n  popular,\n  studentCount,\n  "lessonCount": count(modules[].lessons[]),\n  "moduleCount": count(modules),\n  "totalDuration": math::sum(modules[].lessons[]->duration)\n\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  "coverImageUrl": coverImage.asset->url,\n  "coverImageAlt": coverImage.alt,\n  "category": category->{ _id, title, "slug": slug.current },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  price,\n  popular,\n  studentCount,\n  "lessonCount": count(modules[].lessons[]),\n  "moduleCount": count(modules),\n  "totalDuration": math::sum(modules[].lessons[]->duration)\n,\n    "learningOutcomes": learningOutcomes[] { _key, icon, title, description },\n    "modules": modules[] { _key, title, summary, "lessons": lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  duration,\n  freePreview\n } }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)].slug.current\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current) && instructor._ref == $instructorId]\n  | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  "coverImageUrl": coverImage.asset->url,\n  "coverImageAlt": coverImage.alt,\n  "category": category->{ _id, title, "slug": slug.current },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  price,\n  popular,\n  studentCount,\n  "lessonCount": count(modules[].lessons[]),\n  "moduleCount": count(modules),\n  "totalDuration": math::sum(modules[].lessons[]->duration)\n\n  }\n': COURSES_BY_INSTRUCTOR_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current) && category._ref == $categoryId]\n  | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  "coverImageUrl": coverImage.asset->url,\n  "coverImageAlt": coverImage.alt,\n  "category": category->{ _id, title, "slug": slug.current },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  price,\n  popular,\n  studentCount,\n  "lessonCount": count(modules[].lessons[]),\n  "moduleCount": count(modules),\n  "totalDuration": math::sum(modules[].lessons[]->duration)\n\n  }\n': COURSES_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    icon,\n    "courseCount": count(\n      *[_type == "course" && references(^._id)]\n    )\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    icon,\n    "courses": *[_type == "course" && references(^._id)] | order(title asc) {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  "coverImageUrl": coverImage.asset->url,\n  "coverImageAlt": coverImage.alt,\n  "category": category->{ _id, title, "slug": slug.current },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  price,\n  popular,\n  studentCount,\n  "lessonCount": count(modules[].lessons[]),\n  "moduleCount": count(modules),\n  "totalDuration": math::sum(modules[].lessons[]->duration)\n\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    title,\n    bio,\n    "photoUrl": photo.asset->url,\n    expertise,\n    "socialLinks": socialLinks[] { _key, platform, url },\n    "courseCount": count(\n      *[_type == "course" && references(^._id)]\n    )\n  }\n': INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    title,\n    bio,\n    "photoUrl": photo.asset->url,\n    expertise,\n    "socialLinks": socialLinks[] { _key, platform, url },\n    "courses": *[_type == "course" && references(^._id)] | order(title asc) {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  level,\n  "coverImageUrl": coverImage.asset->url,\n  "coverImageAlt": coverImage.alt,\n  "category": category->{ _id, title, "slug": slug.current },\n  "instructor": instructor->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  price,\n  popular,\n  studentCount,\n  "lessonCount": count(modules[].lessons[]),\n  "moduleCount": count(modules),\n  "totalDuration": math::sum(modules[].lessons[]->duration)\n\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    "thumbnailUrl": thumbnail.asset->url,\n    duration,\n    freePreview,\n    studentCount,\n    "notes": notes[] {\n      _type == "image" => {\n        _type,\n        _key,\n        "url": asset->url,\n        alt,\n        caption\n      },\n      _type != "image" => @\n    },\n    keyPoints,\n    proTip,\n    "resources": resources[] { _key, type, title, description, url },\n    "course": *[_type == "course" && references(^._id)][0] {\n      _id,\n      title,\n      "slug": slug.current,\n      level,\n      studentCount,\n      "coverImageUrl": coverImage.asset->url,\n      "modules": modules[] {\n        _key,\n        title,\n        summary,\n        "lessons": lessons[]-> {\n          _id,\n          title,\n          "slug": slug.current,\n          duration,\n          freePreview\n        }\n      }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)].slug.current\n': LESSON_SLUGS_QUERY_RESULT;
  }
}
