/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  title?: string;
  bio?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  socialLinks?: Array<{
    platform: "website" | "github" | "x" | "linkedin" | "youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  lessonType: "video" | "text" | "quiz";
  durationMinutes?: number;
  summary?: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  videoUrl?: string;
  questions?: Array<{
    prompt: string;
    options?: Array<{
      text?: string;
      correct?: boolean;
      _type: "answerOption";
      _key: string;
    }>;
    explanation?: string;
    _type: "question";
    _key: string;
  }>;
  resources?: Array<{
    label?: string;
    resourceType?: "link" | "file";
    url?: string;
    file?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    _type: "resource";
    _key: string;
  }>;
};

export type CourseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "course";
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _id: string;
  _type: "module";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  course: CourseReference;
  description?: string;
  position: number;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  subtitle?: string;
  description?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category: CategoryReference;
  instructors?: Array<
    {
      _key: string;
    } & InstructorReference
  >;
  difficulty: "beginner" | "intermediate" | "advanced";
  status: "draft" | "published";
  estimatedDurationMinutes?: number;
  highlights?: Array<{
    label?: string;
    _type: "highlight";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  icon?:
    | "nextjs"
    | "docker"
    | "typescript"
    | "react"
    | "nodejs"
    | "database"
    | "devops";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Instructor
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityFileAssetReference
  | Lesson
  | CourseReference
  | LessonReference
  | Module
  | CategoryReference
  | InstructorReference
  | Course
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && status == "published" && defined(slug.current)]  | order(title asc) {      _id,  title,  "slug": slug.current,  subtitle,  difficulty,  "coverImageUrl": coverImage.asset->url,  "category": category->{ _id, title, "slug": slug.current, icon },  "instructors": instructors[]->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  "estimatedDurationMinutes": estimatedDurationMinutes,  "highlights": highlights[] { _key, label },    "moduleCount": count(*[_type == "module" && course._ref == ^._id])  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  subtitle: string | null;
  difficulty: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
    icon:
      | "database"
      | "devops"
      | "docker"
      | "nextjs"
      | "nodejs"
      | "react"
      | "typescript"
      | null;
  };
  instructors: Array<{
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  }> | null;
  estimatedDurationMinutes: number | null;
  highlights: Array<{
    _key: string;
    label: string | null;
  }> | null;
  moduleCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: COURSE_BY_SLUG_QUERY
// Query: *[_type == "course" && slug.current == $slug && status == "published"][0] {      _id,  title,  "slug": slug.current,  subtitle,  difficulty,  "coverImageUrl": coverImage.asset->url,  "category": category->{ _id, title, "slug": slug.current, icon },  "instructors": instructors[]->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  "estimatedDurationMinutes": estimatedDurationMinutes,  "highlights": highlights[] { _key, label },    description,    "modules": *[_type == "module" && course._ref == ^._id] | order(position asc) {        _id,  title,  description,  position,  "lessons": lessons[]->{   _id,  title,  "slug": slug.current,  lessonType,  durationMinutes,  summary }    }  }
export type COURSE_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  subtitle: string | null;
  difficulty: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
    icon:
      | "database"
      | "devops"
      | "docker"
      | "nextjs"
      | "nodejs"
      | "react"
      | "typescript"
      | null;
  };
  instructors: Array<{
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  }> | null;
  estimatedDurationMinutes: number | null;
  highlights: Array<{
    _key: string;
    label: string | null;
  }> | null;
  description: string | null;
  modules: Array<{
    _id: string;
    title: string;
    description: string | null;
    position: number;
    lessons: Array<{
      _id: string;
      title: string;
      slug: string;
      lessonType: "quiz" | "text" | "video";
      durationMinutes: number | null;
      summary: string | null;
    }> | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && status == "published" && defined(slug.current)].slug.current
export type COURSE_SLUGS_QUERY_RESULT = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: COURSES_BY_INSTRUCTOR_QUERY
// Query: *[_type == "course" && status == "published" && defined(slug.current) && $instructorId in instructors[]._ref]  | order(title asc) {      _id,  title,  "slug": slug.current,  subtitle,  difficulty,  "coverImageUrl": coverImage.asset->url,  "category": category->{ _id, title, "slug": slug.current, icon },  "instructors": instructors[]->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  "estimatedDurationMinutes": estimatedDurationMinutes,  "highlights": highlights[] { _key, label }  }
export type COURSES_BY_INSTRUCTOR_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  subtitle: string | null;
  difficulty: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
    icon:
      | "database"
      | "devops"
      | "docker"
      | "nextjs"
      | "nodejs"
      | "react"
      | "typescript"
      | null;
  };
  instructors: Array<{
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  }> | null;
  estimatedDurationMinutes: number | null;
  highlights: Array<{
    _key: string;
    label: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: COURSES_BY_CATEGORY_QUERY
// Query: *[_type == "course" && status == "published" && defined(slug.current) && category._ref == $categoryId]  | order(title asc) {      _id,  title,  "slug": slug.current,  subtitle,  difficulty,  "coverImageUrl": coverImage.asset->url,  "category": category->{ _id, title, "slug": slug.current, icon },  "instructors": instructors[]->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  "estimatedDurationMinutes": estimatedDurationMinutes,  "highlights": highlights[] { _key, label }  }
export type COURSES_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  subtitle: string | null;
  difficulty: "advanced" | "beginner" | "intermediate";
  coverImageUrl: string | null;
  category: {
    _id: string;
    title: string;
    slug: string;
    icon:
      | "database"
      | "devops"
      | "docker"
      | "nextjs"
      | "nodejs"
      | "react"
      | "typescript"
      | null;
  };
  instructors: Array<{
    _id: string;
    name: string;
    slug: string;
    title: string | null;
    photoUrl: string | null;
  }> | null;
  estimatedDurationMinutes: number | null;
  highlights: Array<{
    _key: string;
    label: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    icon,    "courseCount": count(      *[_type == "course" && status == "published" && references(^._id)]    )  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  icon:
    | "database"
    | "devops"
    | "docker"
    | "nextjs"
    | "nodejs"
    | "react"
    | "typescript"
    | null;
  courseCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[_type == "category" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    icon,    "courses": *[_type == "course" && status == "published" && references(^._id)] | order(title asc) {        _id,  title,  "slug": slug.current,  subtitle,  difficulty,  "coverImageUrl": coverImage.asset->url,  "category": category->{ _id, title, "slug": slug.current, icon },  "instructors": instructors[]->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  "estimatedDurationMinutes": estimatedDurationMinutes,  "highlights": highlights[] { _key, label }    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  icon:
    | "database"
    | "devops"
    | "docker"
    | "nextjs"
    | "nodejs"
    | "react"
    | "typescript"
    | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    subtitle: string | null;
    difficulty: "advanced" | "beginner" | "intermediate";
    coverImageUrl: string | null;
    category: {
      _id: string;
      title: string;
      slug: string;
      icon:
        | "database"
        | "devops"
        | "docker"
        | "nextjs"
        | "nodejs"
        | "react"
        | "typescript"
        | null;
    };
    instructors: Array<{
      _id: string;
      name: string;
      slug: string;
      title: string | null;
      photoUrl: string | null;
    }> | null;
    estimatedDurationMinutes: number | null;
    highlights: Array<{
      _key: string;
      label: string | null;
    }> | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: INSTRUCTORS_QUERY
// Query: *[_type == "instructor"] | order(name asc) {    _id,    name,    "slug": slug.current,    title,    bio,    "photoUrl": photo.asset->url,    "socialLinks": socialLinks[] { _key, platform, url },    "courseCount": count(      *[_type == "course" && status == "published" && references(^._id)]    )  }
export type INSTRUCTORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  title: string | null;
  bio: string | null;
  photoUrl: string | null;
  socialLinks: Array<{
    _key: string;
    platform: "github" | "linkedin" | "website" | "x" | "youtube";
    url: string | null;
  }> | null;
  courseCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: INSTRUCTOR_BY_SLUG_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    title,    bio,    "photoUrl": photo.asset->url,    "socialLinks": socialLinks[] { _key, platform, url },    "courses": *[_type == "course" && status == "published" && references(^._id)] | order(title asc) {        _id,  title,  "slug": slug.current,  subtitle,  difficulty,  "coverImageUrl": coverImage.asset->url,  "category": category->{ _id, title, "slug": slug.current, icon },  "instructors": instructors[]->{   _id,  name,  "slug": slug.current,  title,  "photoUrl": photo.asset->url },  "estimatedDurationMinutes": estimatedDurationMinutes,  "highlights": highlights[] { _key, label }    }  }
export type INSTRUCTOR_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  title: string | null;
  bio: string | null;
  photoUrl: string | null;
  socialLinks: Array<{
    _key: string;
    platform: "github" | "linkedin" | "website" | "x" | "youtube";
    url: string | null;
  }> | null;
  courses: Array<{
    _id: string;
    title: string;
    slug: string;
    subtitle: string | null;
    difficulty: "advanced" | "beginner" | "intermediate";
    coverImageUrl: string | null;
    category: {
      _id: string;
      title: string;
      slug: string;
      icon:
        | "database"
        | "devops"
        | "docker"
        | "nextjs"
        | "nodejs"
        | "react"
        | "typescript"
        | null;
    };
    instructors: Array<{
      _id: string;
      name: string;
      slug: string;
      title: string | null;
      photoUrl: string | null;
    }> | null;
    estimatedDurationMinutes: number | null;
    highlights: Array<{
      _key: string;
      label: string | null;
    }> | null;
  }>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: MODULES_BY_COURSE_QUERY
// Query: *[_type == "module" && course._ref == $courseId] | order(position asc) {      _id,  title,  description,  position,  "lessons": lessons[]->{   _id,  title,  "slug": slug.current,  lessonType,  durationMinutes,  summary }  }
export type MODULES_BY_COURSE_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  description: string | null;
  position: number;
  lessons: Array<{
    _id: string;
    title: string;
    slug: string;
    lessonType: "quiz" | "text" | "video";
    durationMinutes: number | null;
    summary: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: LESSON_BY_SLUG_QUERY
// Query: *[_type == "lesson" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    lessonType,    durationMinutes,    summary,    videoUrl,    "content": content[] {      _type == "image" => {        _type,        _key,        "url": asset->url,        alt,        caption      },      _type != "image" => @    },    "questions": questions[] {      _key,      prompt,      "options": options[] { _key, text, correct },      explanation    },    "resources": resources[] { _key, label, resourceType, url, "fileUrl": file.asset->url },    "module": *[_type == "module" && references(^._id)][0] {      _id,      title,      position,      "course": course->{ _id, title, "slug": slug.current }    }  }
export type LESSON_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  lessonType: "quiz" | "text" | "video";
  durationMinutes: number | null;
  summary: string | null;
  videoUrl: string | null;
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _type: "image";
        _key: string;
        url: string | null;
        alt: string | null;
        caption: string | null;
      }
  > | null;
  questions: Array<{
    _key: string;
    prompt: string;
    options: Array<{
      _key: string;
      text: string | null;
      correct: boolean | null;
    }> | null;
    explanation: string | null;
  }> | null;
  resources: Array<{
    _key: string;
    label: string | null;
    resourceType: "file" | "link" | null;
    url: string | null;
    fileUrl: string | null;
  }> | null;
  module: {
    _id: string;
    title: string;
    position: number;
    course: {
      _id: string;
      title: string;
      slug: string;
    };
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: LESSON_SLUGS_QUERY
// Query: *[_type == "lesson" && defined(slug.current)].slug.current
export type LESSON_SLUGS_QUERY_RESULT = Array<string>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && status == "published" && defined(slug.current)]\n  | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  difficulty,\n  "coverImageUrl": coverImage.asset->url,\n  "category": category->{ _id, title, "slug": slug.current, icon },\n  "instructors": instructors[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  "estimatedDurationMinutes": estimatedDurationMinutes,\n  "highlights": highlights[] { _key, label }\n,\n    "moduleCount": count(*[_type == "module" && course._ref == ^._id])\n  }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug && status == "published"][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  difficulty,\n  "coverImageUrl": coverImage.asset->url,\n  "category": category->{ _id, title, "slug": slug.current, icon },\n  "instructors": instructors[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  "estimatedDurationMinutes": estimatedDurationMinutes,\n  "highlights": highlights[] { _key, label }\n,\n    description,\n    "modules": *[_type == "module" && course._ref == ^._id] | order(position asc) {\n      \n  _id,\n  title,\n  description,\n  position,\n  "lessons": lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  lessonType,\n  durationMinutes,\n  summary\n }\n\n    }\n  }\n': COURSE_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "course" && status == "published" && defined(slug.current)].slug.current\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && status == "published" && defined(slug.current) && $instructorId in instructors[]._ref]\n  | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  difficulty,\n  "coverImageUrl": coverImage.asset->url,\n  "category": category->{ _id, title, "slug": slug.current, icon },\n  "instructors": instructors[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  "estimatedDurationMinutes": estimatedDurationMinutes,\n  "highlights": highlights[] { _key, label }\n\n  }\n': COURSES_BY_INSTRUCTOR_QUERY_RESULT;
    '\n  *[_type == "course" && status == "published" && defined(slug.current) && category._ref == $categoryId]\n  | order(title asc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  difficulty,\n  "coverImageUrl": coverImage.asset->url,\n  "category": category->{ _id, title, "slug": slug.current, icon },\n  "instructors": instructors[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  "estimatedDurationMinutes": estimatedDurationMinutes,\n  "highlights": highlights[] { _key, label }\n\n  }\n': COURSES_BY_CATEGORY_QUERY_RESULT;
    '\n  *[_type == "category"] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    icon,\n    "courseCount": count(\n      *[_type == "course" && status == "published" && references(^._id)]\n    )\n  }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "category" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    icon,\n    "courses": *[_type == "course" && status == "published" && references(^._id)] | order(title asc) {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  difficulty,\n  "coverImageUrl": coverImage.asset->url,\n  "category": category->{ _id, title, "slug": slug.current, icon },\n  "instructors": instructors[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  "estimatedDurationMinutes": estimatedDurationMinutes,\n  "highlights": highlights[] { _key, label }\n\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "instructor"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    title,\n    bio,\n    "photoUrl": photo.asset->url,\n    "socialLinks": socialLinks[] { _key, platform, url },\n    "courseCount": count(\n      *[_type == "course" && status == "published" && references(^._id)]\n    )\n  }\n': INSTRUCTORS_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    title,\n    bio,\n    "photoUrl": photo.asset->url,\n    "socialLinks": socialLinks[] { _key, platform, url },\n    "courses": *[_type == "course" && status == "published" && references(^._id)] | order(title asc) {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  subtitle,\n  difficulty,\n  "coverImageUrl": coverImage.asset->url,\n  "category": category->{ _id, title, "slug": slug.current, icon },\n  "instructors": instructors[]->{ \n  _id,\n  name,\n  "slug": slug.current,\n  title,\n  "photoUrl": photo.asset->url\n },\n  "estimatedDurationMinutes": estimatedDurationMinutes,\n  "highlights": highlights[] { _key, label }\n\n    }\n  }\n': INSTRUCTOR_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "module" && course._ref == $courseId] | order(position asc) {\n    \n  _id,\n  title,\n  description,\n  position,\n  "lessons": lessons[]->{ \n  _id,\n  title,\n  "slug": slug.current,\n  lessonType,\n  durationMinutes,\n  summary\n }\n\n  }\n': MODULES_BY_COURSE_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    lessonType,\n    durationMinutes,\n    summary,\n    videoUrl,\n    "content": content[] {\n      _type == "image" => {\n        _type,\n        _key,\n        "url": asset->url,\n        alt,\n        caption\n      },\n      _type != "image" => @\n    },\n    "questions": questions[] {\n      _key,\n      prompt,\n      "options": options[] { _key, text, correct },\n      explanation\n    },\n    "resources": resources[] { _key, label, resourceType, url, "fileUrl": file.asset->url },\n    "module": *[_type == "module" && references(^._id)][0] {\n      _id,\n      title,\n      position,\n      "course": course->{ _id, title, "slug": slug.current }\n    }\n  }\n': LESSON_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "lesson" && defined(slug.current)].slug.current\n': LESSON_SLUGS_QUERY_RESULT;
  }
}
